"""add unique constraints

Revision ID: 0001
Revises: 
Create Date: 2026-04-29 08:48:42.387392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bet_user_match', 'bets', ['user_id', 'match_id'])
    op.create_unique_constraint('uq_group_team', 'group_teams', ['group_id', 'team_id'])
    op.create_unique_constraint('uq_match_number', 'matches', ['match_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_match_number', 'matches', type_='unique')
    op.drop_constraint('uq_group_team', 'group_teams', type_='unique')
    op.drop_constraint('uq_bet_user_match', 'bets', type_='unique')
    # ### end Alembic commands ###
